# Playbook for change the DNS server into the file /etc/resolv.conf
# change-dns-server.yml
---

- hosts: <hosts>  #ADD the (group) host
  remote_user: ansible
  become: yes

  tasks:
  - name: 1. Copy file resolv.conf
    shell: cp /etc/resolv.conf /etc/resolv.conf.copy
  - name: 2. Change IP server DNS
    shell: sed -i "s|<old_IP_DNS_server|new_IP_DNS_server|g" /etc/resolv.conf #ADD the IPs
