# Change the password of a user
# It's possible to comment the vars and use it in command line : --extra-vars "user=<user> password=<passwd>"
# change-user-password.yml
---

- hosts: <hosts> #ADD the (group) host
  remote_user: ansible
  become: yes

  vars:
    user: <ID_user> #ADD the user
    password: <passwd>  #ADD the password

  tasks:
  - name: 1. Generate the passwd in SHA512 with salt
    shell: python3 -c 'import crypt; print(crypt.crypt("{{ password }}", crypt.mksalt(crypt.METHOD_SHA512)))'
    register: hash_passwd

  - name: 2. Change the passwd of {{ user }}
    user:
      name={{ user }}
      update_password=always
      password={{hash_passwd.stdout}}
