# Change the password of a user
# change-user-password.yml
---

- hosts: <hosts> #ADD the (group) host
  remote_user: ansible
  become: yes

  vars:
    user: <ID_user> #ADD the user

  tasks:
  - name: 1. Generate the passwd in SHA512 with salt
    shell: python3 -c 'import crypt; print(crypt.crypt("<passwd>", crypt.mksalt(crypt.METHOD_SHA512)))' #ADD the password
    register: hash_passwd

  - name: 2. Change the passwd of {{ user }}
    user:
      name={{ user }}
      update_password=always
      password={{hash_passwd.stdout}}
