# Simple create-user like adduser and the password is the ID of the user
# create-user-simple.yml
---

- hosts: <hosts>
  remote_user: ansible
  become: yes

  vars:
    user: <ID_new_user>

  tasks:
  - name: 1. Create group {{ user }}
    shell: groupadd {{ user }}

  - name: 2. Create user {{ user }}
    shell: useradd -g {{ user }} -s /bin/bash -d /home/{{ user }} -m {{ user }}

  - name: 3. Generate the passwd
    shell: openssl passwd -1 -salt 3Zdze7Vx {{ user }}
    register: hash_passwd

  - name: 3.1 Passwd to {{ user }} is {{ user }}
    user:
      name={{ user }}
      update_password=always
      password={{hash_passwd.stdout}}
