# create-user.yml
---

- hosts: 
  remote_user: 
  become: yes

  vars:
    user: <ID_new_user>

  tasks:
  - name: 1. Create group {{ user }}
    shell: groupadd {{ user }}

  - name: 2. Create user {{ user }}
    shell: useradd -g {{ user }} -s /bin/bash -d /home/{{ user }} -m {{ user }}

# Generate the pass with:
# openssl passwd -1 -salt 3Zdze7Vx <passwd>
  - name: 3. Passwd to {{ user }}
    user:
      name={{ user }}
      update_password=always
      password=<add_result_of_the_command_openssl>
