# Install packages ...
# install-packages.yml
---

- hosts: <hosts>  #ADD the (group) host
  remote_user: ansible
  become: yes

  tasks:
  - name: 1. Update (command: apt-get update)
    apt:
      update_cache: yes

  - name: 2. Installation (command: apt-get install...)
    apt:
      name: "{{ packages }}"
  vars:
    packages:
    - pack1
    - pack2
